force-app/main/default/objects/PD_Approval__c/PD_Approval__c.object-meta.xml
<CustomObject>
    <label>PD Approval</label>
    <nameField>
        <displayFormat>PDA-{0000}</displayFormat>
        <label>PD Approval ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PD Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PD_Approval__c/fields/Additional_BR_Contributions__c.field-meta.xml
<CustomField>
    <fullName>Additional_BR_Contributions__c</fullName>
    <inlineHelpText>Additional contribution from Better Rehab outside of the employee&apos;s total PD balance. If not applicable, enter 0.</inlineHelpText>
    <label>Additional BR Contribution</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PD_Approval__c/fields/Approver_Contact__c.field-meta.xml
<CustomField>
    <fullName>Approver_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Approver Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PD Approvals</relationshipLabel>
    <relationshipName>PD_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PD_Approval__c/fields/Cost_from_Employee_s_Total_PD__c.field-meta.xml
<CustomField>
    <fullName>Cost_from_Employee_s_Total_PD__c</fullName>
    <inlineHelpText>Cost to be deducted from the employee&apos;s total PD balance (Annual PD + Better Rewards PD). If not applicable, enter 0.</inlineHelpText>
    <label>Cost from Employee&apos;s Total PD</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PD_Approval__c/fields/Cost_of_Course__c.field-meta.xml
<CustomField>
    <fullName>Cost_of_Course__c</fullName>
    <formula>PD_Request__r.Cost_of_Course__c</formula>
    <label>Cost of Course</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PD_Approval__c/fields/PD_Request__c.field-meta.xml
<CustomField>
    <fullName>PD_Request__c</fullName>
    <label>PD Request</label>
    <referenceTo>PD_Request__c</referenceTo>
    <relationshipLabel>PD Approvals</relationshipLabel>
    <relationshipName>PD_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PD_Approval__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <formula>CASE(Approver_Contact__r.Id,
PD_Request__r.Regional_Manager__c, &apos;Regional Manager&apos;,
PD_Request__r.State_Manager__c, &apos;State Manager&apos;,
PD_Request__r.Principal_Clinician__c, &apos;Principal Clinician&apos;,
PD_Request__r.Dept_Manager_ID__c , &apos;Department Manager&apos;,
PD_Request__r.Direct_Supervisor_ID__c, IF(PD_Request__r.Direct_Supervisor_ID__c = PD_Request__r.Regional_Manager__c, &apos;Regional Manager&apos;, &apos;Direct Supervisor&apos;),
&apos;N/A&apos;
)</formula>
    <label>Position</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/PD_Request__c.object-meta.xml
<CustomObject>
    <label>PD Request</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>PD Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PD Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PD_Request__c/fields/Cost_of_Course__c.field-meta.xml
<CustomField>
    <fullName>Cost_of_Course__c</fullName>
    <label>Cost of Course</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Direct_Supervisor_ID__c.field-meta.xml
<CustomField>
    <fullName>Direct_Supervisor_ID__c</fullName>
    <formula>IF(TEXT(Employee_Name__r.Direct_Supervisor__r.Internal_Banding__c) = &apos;Director&apos; &amp;&amp; RecordType.DeveloperName != &apos;Leadership&apos;, &apos;&apos;, Employee_Name__r.Direct_Supervisor__c)</formula>
    <label>Direct Supervisor ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Worker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PD Requests</relationshipLabel>
    <relationshipName>PD_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Principal_Clinician__c.field-meta.xml
<CustomField>
    <fullName>Principal_Clinician__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Principal Clinician</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Worker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PD Requests (Principal Clinician)</relationshipLabel>
    <relationshipName>PD_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Regional_Manager__c.field-meta.xml
<CustomField>
    <fullName>Regional_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regional Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Worker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PD Requests (Regional Manager)</relationshipLabel>
    <relationshipName>PD_Requests3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PD_Request__c/recordTypes/Allied_Health_Assistant.recordType-meta.xml
<RecordType>
    <fullName>Allied_Health_Assistant</fullName>
    <active>true</active>
    <description>For AHAs</description>
    <label>Allied Health Assistant</label>
</RecordType>

force-app/main/default/objects/PD_Request__c/recordTypes/Clinician.recordType-meta.xml
<RecordType>
    <fullName>Clinician</fullName>
    <active>true</active>
    <description>For clinicians and team leaders only</description>
    <label>Clinician</label>
</RecordType>

force-app/main/default/objects/PD_Request__c/recordTypes/Leadership.recordType-meta.xml
<RecordType>
    <fullName>Leadership</fullName>
    <active>true</active>
    <description>For RMs, NCLs, SMs and HST State Leads</description>
    <label>Leadership</label>
</RecordType>

force-app/main/default/objects/PD_Request__c/recordTypes/Operational.recordType-meta.xml
<RecordType>
    <fullName>Operational</fullName>
    <active>true</active>
    <description>For operational staff (Office managers, P&amp;C, Marketing, IT)</description>
    <label>Operational</label>
</RecordType>

force-app/main/default/objects/PD_Request__c/recordTypes/Principal_Clinician.recordType-meta.xml
<RecordType>
    <fullName>Principal_Clinician</fullName>
    <active>true</active>
    <description>For principal clinicians</description>
    <label>Principal Clinician</label>
</RecordType>

force-app/main/default/classes/BR_PDApprovalCreation.cls
public with sharing class BR_PDApprovalCreation {
    //This class is for creating approval when a PD Request is first lodged and when subsequent approval has to be created
    List<PD_Approval__c> approvals;
    List<PD_Request__c> updatedPDRequests;
	List<RecordType> pdRequestList = new List<RecordType>();
    Map<String,Id> pdRequestType = new Map<String,Id>();    
    
    public BR_PDApprovalCreation(List<PD_Request__c> newPDRequests) {
        
        approvals = new List<PD_Approval__c>();
        updatedPDRequests = new List<PD_Request__c>();
        
        List<PD_Request__c> incomingRequests = [SELECT id, Cost_of_Course__c, Employee_Name__c, Employee_Name__r.Total_Remaining_PD_Balance__c, RecordTypeID, Regional_Manager__c, Principal_Clinician__c, Direct_Supervisor_ID__c FROM PD_Request__c WHERE id IN :newPDRequests];
        List<PD_Approval__c> existingApprovals = [SELECT id, Position__c, Status__c FROM PD_Approval__c WHERE PD_Request__c IN :newPDRequests];   //COLLECT MORE FIELDS HERE PLS
        
        pdRequestList = [SELECT Id, DeveloperName, SObjectType FROM RecordType WHERE SObjectType = 'PD_Request__c'];
        for(RecordType ids : pdRequestList){
            pdRequestType.put(ids.DeveloperName, ids.Id);
        }
        
        //Check whose approval to create based on the record type - this part of the code only runs for newly created PD request, as triggered in PD request trigger
        for (Integer i = 0; i < incomingRequests.size(); i++) {  
            System.debug('Record type ID is: ' + incomingRequests[i].RecordTypeId);
                
           	//Record Type 1 = Clinician
            if(incomingRequests[i].RecordTypeId == pdRequestType.get('Clinician')){
                if(existingApprovals.size() == 0){ 
                    PD_Approval__c pcApproval = createRecord(incomingRequests[i],incomingRequests[i].Principal_Clinician__c, null);  
                    approvals.add(pcApproval);   
                    System.debug('Clinician: Creating PC Approval');
                }      
            }
            
            //Record Type 2 and 3 = PC and Leadership
            if(incomingRequests[i].RecordTypeId == pdRequestType.get('Principal_Clinician') || incomingRequests[i].RecordTypeId == pdRequestType.get('Leadership')){
                if(existingApprovals.size() == 0){
                    PD_Approval__c dsApproval = createRecord(incomingRequests[i],incomingRequests[i].Direct_Supervisor_ID__c, null);  
                    approvals.add(dsApproval);     
                    System.debug('PC or Leadership: Creating DS Approval');
                }                
            }
            
            //Record Type 4 = AHA
            if(incomingRequests[i].RecordTypeId == pdRequestType.get('Allied_Health_Assistant')){
                if(existingApprovals.size() == 0){                    
                    PD_Approval__c rmApproval = createRecord(incomingRequests[i],incomingRequests[i].Regional_Manager__c, null);  
                    approvals.add(rmApproval);     
                    System.debug('AHA: Creating RM Approval');
                }
            }
            
            //Record Type 5 = Operational
            if(incomingRequests[i].RecordTypeId == pdRequestType.get('Operational')){
                if(existingApprovals.size() == 0){  
                    PD_Approval__c dsApproval = createRecord(incomingRequests[i], incomingRequests[i].Direct_Supervisor_ID__c, null);  
                    approvals.add(dsApproval);     
                    System.debug('Operational: Creating DS Approval');  
                }      
            }                            
                        
        }   
        
        insert approvals;   
        update updatedPDRequests;
    }
    
    //this method is called from within this class and BR_PDApproval class to create subsequent PD approvals
    //add PD_Approval__c prevApproval as the 3rd param - put null for the above code    
    public PD_Approval__c createRecord(PD_Request__c pdRequest, Id supervisorId, PD_Approval__c prevApproval){
        PD_Approval__c newApproval = new PD_Approval__c();
        
        if(supervisorId != NULL){ 
            newApproval.Approver_Contact__c = supervisorId;
            newApproval.Status__c = 'Pending';
            newApproval.PD_Request__c = pdRequest.Id;                         
        } 
        
        //if prevApproval == NULL, this means we are making the 1st approval record for this PD request
        if(prevApproval == NULL){
            //we want to pre-fill the PD Approval cost fields to make it easier for users to approve
            if(pdRequest.Cost_of_Course__c <= pdRequest.Employee_Name__r.Total_Remaining_PD_Balance__c){
                newApproval.Additional_BR_Contributions__c = 0;
                newApproval.Cost_from_Employee_s_Total_PD__c = pdRequest.Cost_of_Course__c;
            } else if(pdRequest.Cost_of_Course__c > pdRequest.Employee_Name__r.Total_Remaining_PD_Balance__c){
                newApproval.Additional_BR_Contributions__c = 0;
                newApproval.Cost_from_Employee_s_Total_PD__c = pdRequest.Employee_Name__r.Total_Remaining_PD_Balance__c;
            }
        } else {
            newApproval.Additional_BR_Contributions__c = prevApproval.Additional_BR_Contributions__c;
            newApproval.Cost_from_Employee_s_Total_PD__c = prevApproval.Cost_from_Employee_s_Total_PD__c;
        }        
        
        System.debug('Supervisor ID is not null and PDA is created with the ID of: ' + newApproval.Id);      
        return newApproval; 
    }   
    
  }