force-app/main/default/objects/PD_Approval__c/PD_Approval__c.object-meta.xml
<CustomObject>
    <label>PD Approval</label>
    <nameField>
        <displayFormat>PDA-{0000}</displayFormat>
        <label>PD Approval ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PD Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PD_Approval__c/fields/Additional_BR_Contributions__c.field-meta.xml
<CustomField>
    <fullName>Additional_BR_Contributions__c</fullName>
    <inlineHelpText>Additional contribution from Better Rehab outside of the employee&apos;s total PD balance. If not applicable, enter 0.</inlineHelpText>
    <label>Additional BR Contribution</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PD_Approval__c/fields/Bypass_Validation_Rule__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Validation_Rule__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Only check this for APEX test purposes</inlineHelpText>
    <label>Bypass Validation Rule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PD_Approval__c/fields/Cost_from_Employee_s_Total_PD__c.field-meta.xml
<CustomField>
    <fullName>Cost_from_Employee_s_Total_PD__c</fullName>
    <inlineHelpText>Cost to be deducted from the employee&apos;s total PD balance (Annual PD + Better Rewards PD). If not applicable, enter 0.</inlineHelpText>
    <label>Cost from Employee&apos;s Total PD</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PD_Approval__c/fields/Cost_of_Course__c.field-meta.xml
<CustomField>
    <fullName>Cost_of_Course__c</fullName>
    <formula>PD_Request__r.Cost_of_Course__c</formula>
    <label>Cost of Course</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PD_Approval__c/fields/Course_Date_1__c.field-meta.xml
<CustomField>
    <fullName>Course_Date_1__c</fullName>
    <formula>PD_Request__r.Course_Date_1__c</formula>
    <label>Course Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PD_Approval__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <formula>TEXT(PD_Request__r.Course_Name__c)</formula>
    <label>Course Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PD_Approval__c/fields/PD_Request__c.field-meta.xml
<CustomField>
    <fullName>PD_Request__c</fullName>
    <label>PD Request</label>
    <referenceTo>PD_Request__c</referenceTo>
    <relationshipLabel>PD Approvals</relationshipLabel>
    <relationshipName>PD_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PD_Approval__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <formula>CASE(Approver_Contact__r.Id,
PD_Request__r.Regional_Manager__c, &apos;Regional Manager&apos;,
PD_Request__r.State_Manager__c, &apos;State Manager&apos;,
PD_Request__r.Principal_Clinician__c, &apos;Principal Clinician&apos;,
PD_Request__r.Dept_Manager_ID__c , &apos;Department Manager&apos;,
PD_Request__r.Direct_Supervisor_ID__c, IF(PD_Request__r.Direct_Supervisor_ID__c = PD_Request__r.Regional_Manager__c, &apos;Regional Manager&apos;, &apos;Direct Supervisor&apos;),
&apos;N/A&apos;
)</formula>
    <label>Position</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PD_Approval__c/fields/Total_Subsidised_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Subsidised_Cost__c</fullName>
    <formula>Additional_BR_Contributions__c +  Cost_from_Employee_s_Total_PD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Subsidised Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/PD_Request__c.object-meta.xml
<CustomObject>
    <label>PD Request</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>PD Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PD Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PD_Request__c/fields/Approved_by_Clinical_Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Approved_by_Clinical_Supervisor__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>By ticking this box, you acknowledge that your PD Request has been approved and discussed with your supervisor</inlineHelpText>
    <label>Approved by Supervisor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Approved_by_Direct_Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Approved_by_Direct_Supervisor__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>By ticking this box, you acknowledge that your PD Request has been approved and discussed with your direct supervisor</inlineHelpText>
    <label>Approved by Direct Supervisor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Cost_of_Course__c.field-meta.xml
<CustomField>
    <fullName>Cost_of_Course__c</fullName>
    <label>Cost of Course</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Course_Date_1__c.field-meta.xml
<CustomField>
    <fullName>Course_Date_1__c</fullName>
    <label>Course Date 1</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <inlineHelpText>If your course is not listed, choose &apos;Other&apos; and write your course name in the below box</inlineHelpText>
    <label>Course Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>First Aid / CPR</fullName>
            </value>
            <value>
                <fullName>Mental Health First Aid</fullName>
            </value>
            <value>
                <fullName>Home Modifications</fullName>
            </value>
            <value>
                <fullName>OT Driver Assessor Course</fullName>
            </value>
            <value>
                <fullName>Assistive Technology</fullName>
            </value>
            <value>
                <fullName>Diagnosis specific training</fullName>
            </value>
            <value>
                <fullName>Therapy interventions</fullName>
            </value>
            <value>
                <fullName>Accredited clinical courses</fullName>
            </value>
            <value>
                <fullName>Leadership skills</fullName>
            </value>
            <value>
                <fullName>Professional governing bodies</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>Other (Please specify)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Direct_Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Direct_Supervisor__c</fullName>
    <formula>IF(TEXT(Employee_Name__r.Direct_Supervisor__r.Internal_Banding__c) = &apos;Director&apos; &amp;&amp; RecordType.DeveloperName != &apos;Leadership&apos;, &apos;&apos;, Employee_Name__r.Direct_Supervisor__r.enrtcr__Full_Name__c)</formula>
    <label>Direct Supervisor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Worker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PD Requests</relationshipLabel>
    <relationshipName>PD_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Internal_Banding__c.field-meta.xml
<CustomField>
    <fullName>Internal_Banding__c</fullName>
    <formula>TEXT(Employee_Name__r.Internal_Banding__c)</formula>
    <label>Internal Banding</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Principal_Clinician__c.field-meta.xml
<CustomField>
    <fullName>Principal_Clinician__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Principal Clinician</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Worker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PD Requests (Principal Clinician)</relationshipLabel>
    <relationshipName>PD_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Regional_Manager__c.field-meta.xml
<CustomField>
    <fullName>Regional_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regional Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Worker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PD Requests (Regional Manager)</relationshipLabel>
    <relationshipName>PD_Requests3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/State_Manager__c.field-meta.xml
<CustomField>
    <fullName>State_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Worker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PD Requests (State Manager)</relationshipLabel>
    <relationshipName>PD_Requests4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Total_Subsidised_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Subsidised_Cost__c</fullName>
    <formula>Cost_from_Annual_PD__c +   Cost_from_Rewards_PD__c +  Additional_BR_Contribution__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Subsidised Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/recordTypes/Allied_Health_Assistant.recordType-meta.xml
<RecordType>
    <fullName>Allied_Health_Assistant</fullName>
    <active>true</active>
    <description>For AHAs</description>
    <label>Allied Health Assistant</label>
</RecordType>

force-app/main/default/objects/PD_Request__c/recordTypes/Clinician.recordType-meta.xml
<RecordType>
    <fullName>Clinician</fullName>
    <active>true</active>
    <description>For clinicians and team leaders only</description>
    <label>Clinician</label>
</RecordType>

force-app/main/default/objects/PD_Request__c/recordTypes/Leadership.recordType-meta.xml
<RecordType>
    <fullName>Leadership</fullName>
    <active>true</active>
    <description>For RMs, NCLs, SMs and HST State Leads</description>
    <label>Leadership</label>
</RecordType>

force-app/main/default/objects/PD_Request__c/recordTypes/Operational.recordType-meta.xml
<RecordType>
    <fullName>Operational</fullName>
    <active>true</active>
    <description>For operational staff (Office managers, P&amp;C, Marketing, IT)</description>
    <label>Operational</label>
</RecordType>

force-app/main/default/objects/PD_Request__c/recordTypes/Principal_Clinician.recordType-meta.xml
<RecordType>
    <fullName>Principal_Clinician</fullName>
    <active>true</active>
    <description>For principal clinicians</description>
    <label>Principal Clinician</label>
</RecordType>

force-app/main/default/classes/BR_PDApprovalTest.cls
@isTest
private class BR_PDApprovalTest {
    @testSetup static void prepData(){
        //Prep the data
        List<RecordType> pdRequestList = new List<RecordType>();
        Map<String,Id> pdRequestType = new Map<String,Id>();

        pdRequestList = [SELECT Id, DeveloperName, SObjectType FROM RecordType WHERE SObjectType = 'PD_Request__c'];
        for(RecordType ids : pdRequestList){
            pdRequestType.put(ids.DeveloperName, ids.Id);
        }

        //Create 6 worker contacts (1 employee, 5 supervisors)
        User x = [SELECT id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1];
        List<Contact> listOfContacts = new List<Contact>();

        for (Integer i = 0 ; i < 8; i++){
            Contact newWorker = TestObjects.createContact(6, 'NDIS');
            newWorker.FirstName = 'newW' + String.valueOf(i);
            newWorker.Email = 'newWorker'+ String.valueOf(i) + '@betterrehab.com.au';
            newWorker.enrtcr__User__c = x.Id;
            newWorker.Annual_PD_Balance__c = 400;
            newWorker.Better_Rewards_PD_Balance__c = 0;

            listOfContacts.add(newWorker);
        }

        //create a director
        Contact newDirector = TestObjects.createContact(6, 'NDIS');
        newDirector.FirstName = 'newDirector';
        newDirector.Email = 'newDirector@betterrehab.com.au';
        newDirector.Internal_Banding__c = 'Director';
        newDirector.enrtcr__User__c = x.Id;

        listOfContacts.add(newDirector);

        insert listOfContacts;

        List<Contact> updatedContacts = new List<Contact>();

        //Set the Ops Mgr to have the internal banding
        Contact om = [SELECT id, Clinical_Supervisor__c, Direct_Supervisor__c FROM Contact WHERE Email = 'newWorker6@betterrehab.com.au'];
        om.Internal_Banding__c = 'Operations Manager';
        updatedContacts.add(om);

        //Set 1 worker to have all 5 supervisors (CS, DS, RM, SM, PC)
        Contact employee = [SELECT id, Clinical_Supervisor__c, Direct_Supervisor__c FROM Contact WHERE Email = 'newWorker0@betterrehab.com.au'];
        Contact cs = [SELECT id, Clinical_Supervisor__c, Direct_Supervisor__c FROM Contact WHERE Email = 'newWorker1@betterrehab.com.au'];
        Contact ds = [SELECT id, Clinical_Supervisor__c, Direct_Supervisor__c FROM Contact WHERE Email = 'newWorker2@betterrehab.com.au'];
        Contact rm = [SELECT id, Clinical_Supervisor__c, Direct_Supervisor__c FROM Contact WHERE Email = 'newWorker3@betterrehab.com.au'];
        Contact sm = [SELECT id, Clinical_Supervisor__c, Direct_Supervisor__c FROM Contact WHERE Email = 'newWorker4@betterrehab.com.au'];
        Contact pc = [SELECT id, Clinical_Supervisor__c, Direct_Supervisor__c FROM Contact WHERE Email = 'newWorker5@betterrehab.com.au'];
        Contact director = [SELECT id, Clinical_Supervisor__c, Direct_Supervisor__c FROM Contact WHERE Email = 'newDirector@betterrehab.com.au'];

       	employee.Clinical_Supervisor__c = cs.Id;
        employee.Direct_Supervisor__c = ds.Id;
        updatedContacts.add(employee);
        ds.Direct_Supervisor__c = rm.Id;
        updatedContacts.add(ds);
        rm.Direct_Supervisor__c = director.Id;
        updatedContacts.add(rm);

        update updatedContacts;

        List<PD_Request__c> listOfPDs = new List<PD_Request__c>();

        //Create PD Request
        //will be approved, should generate 3 approvals
        PD_Request__c newPD1 = new PD_Request__c();
        newPD1.RecordTypeId = pdRequestType.get('Clinician');
        newPD1.Employee_Name__c = employee.Id;
        newPD1.Course_Name__c = 'First Aid / CPR';
        newPD1.Course_Date_1__c = System.today() + 20;
        newPD1.Cost_of_Course__c = 900;
        newPD1.Principal_Clinician__c = pc.Id;
        newPD1.Regional_Manager__c = rm.Id;
        newPD1.State_Manager__c = sm.Id;
        newPD1.Approved_by_Clinical_Supervisor__c = TRUE;
        newPD1.Approved_by_Direct_Supervisor__c = TRUE;
        listOfPDs.add(newPD1);

        //will be approved, should only generate 1 approval (only RM)
        PD_Request__c newPD2 = new PD_Request__c();
        newPD2.RecordTypeId = pdRequestType.get('Principal_Clinician');
        newPD2.Employee_Name__c = employee.Id;
        newPD2.Course_Name__c = 'First Aid / CPR';
        newPD2.Course_Date_1__c = System.today() + 20;
        newPD2.Cost_of_Course__c = 900;
        newPD2.State_Manager__c = sm.Id;
        newPD2.Approved_by_Clinical_Supervisor__c = TRUE;
        newPD2.Approved_by_Direct_Supervisor__c = TRUE;
        listOfPDs.add(newPD2);

        PD_Request__c newPD3 = new PD_Request__c();
        newPD3.RecordTypeId = pdRequestType.get('Allied_Health_Assistant');
        newPD3.Employee_Name__c = employee.Id;
        newPD3.Course_Name__c = 'First Aid / CPR';
        newPD3.Regional_Manager__c = rm.Id;
        newPD3.State_Manager__c = sm.Id;
        newPD3.Course_Date_1__c = System.today() + 20;
        newPD3.Cost_of_Course__c = 900;

        listOfPDs.add(newPD3);

        PD_Request__c newPD4 = new PD_Request__c();
        newPD4.RecordTypeId = pdRequestType.get('Operational');
        newPD4.Employee_Name__c = employee.Id;
        newPD4.Course_Name__c = 'First Aid / CPR';
        newPD4.Course_Date_1__c = System.today() + 20;
        newPD4.Cost_of_Course__c = 800;

        listOfPDs.add(newPD4);

        PD_Request__c newPD5 = new PD_Request__c();
        newPD5.RecordTypeId = pdRequestType.get('Leadership');
        newPD5.Employee_Name__c = employee.Id;
        newPD5.Course_Name__c = 'First Aid / CPR';
        newPD5.Course_Date_1__c = System.today() + 20;
        newPD5.Cost_of_Course__c = 900;
        listOfPDs.add(newPD5);

        insert listOfPDs;
    }

    @isTest static void testClinicianApproval(){
        //1. Get the first approval from principal clinician
        Test.startTest();
        PD_Approval__c approval = [SELECT id, Position__c, PD_Request__c FROM PD_Approval__c WHERE PD_Request__r.RecordType.DeveloperName =: 'Clinician'];

        approval.Cost_from_Employee_s_Total_PD__c = 300;
        approval.Additional_BR_Contributions__c = 600;
        approval.Comment__c = 'Testing PC';
        approval.Bypass_Validation_Rule__c = TRUE;
        System.debug('Get all the PD Request related IDs: ' + approval.PD_Request__c);

        //make it approved
        System.debug('PD1 Position: ' + approval.Position__c);
        approval.Status__c = 'Approved';
        update approval;

        //2. Second approval from regional manager
        PD_Approval__c rmApproval = [SELECT id, Position__c, PD_Request__c FROM PD_Approval__c WHERE PD_Request__c =: approval.PD_Request__c AND Position__c = 'Regional Manager'];

        rmApproval.Comment__c = 'Testing RM';
        rmApproval.Bypass_Validation_Rule__c = TRUE;
        System.debug('Get all the PD Request related IDs: ' + rmApproval.PD_Request__c);

        //make it approved
        System.debug('PD1 Position: ' + rmApproval.Position__c);
        rmApproval.Status__c = 'Approved';
        update rmApproval;

        //3. Third approval from state manager
        PD_Approval__c smApproval = [SELECT id, Position__c, PD_Request__c FROM PD_Approval__c WHERE PD_Request__c =: approval.PD_Request__c AND Position__c = 'State Manager'];

        smApproval.Comment__c = 'Testing SM';
        smApproval.Bypass_Validation_Rule__c = TRUE;
        System.debug('Get all the PD Request related IDs: ' + smApproval.PD_Request__c);

        //make it approved
        System.debug('PD1 Position: ' + smApproval.Position__c);
        smApproval.Status__c = 'Approved';
        update smApproval;
        
        Test.stopTest();

        List<PD_Approval__c> allApprovals = [SELECT id, Position__c, PD_Request__c FROM PD_Approval__c WHERE PD_Request__c =: approval.PD_Request__c]; //2 approvals here
        PD_Request__c req = [SELECT Id, Employee_Name__c, Status__c, Total_Subsidised_Cost__c FROM PD_Request__c WHERE Id =: approval.PD_Request__c];
        Contact e = [SELECT Id, Annual_PD_Balance__c, Better_Rewards_PD_Balance__c FROM Contact WHERE Id =: req.Employee_Name__c];

        System.assertEquals(3, allApprovals.size());
        System.assertEquals('Approved', req.Status__c);
        System.assertEquals(900, req.Total_Subsidised_Cost__c);
        System.assertEquals(100, e.Annual_PD_Balance__c);
        System.assertEquals(0, e.Better_Rewards_PD_Balance__c);
    }

    @isTest static void testPCApproval(){
        Test.startTest();
        //Should only be 1 - FIRST APPROVAL FROM DS
        PD_Approval__c appPC = [SELECT id, Position__c, PD_Request__c FROM PD_Approval__c WHERE PD_Request__r.RecordType.DeveloperName =: 'Principal_Clinician'];

        appPC.Cost_from_Employee_s_Total_PD__c = 400;
        appPC.Additional_BR_Contributions__c = 500;
        appPC.Comment__c = 'Testing PC';
        appPC.Bypass_Validation_Rule__c = TRUE;
        System.debug('Get all the PD Request related IDs: ' + appPC.PD_Request__c);

        //make it approved
        System.debug('PD1 Position: ' + appPC.Position__c);
        appPC.Status__c = 'Approved';
        update appPC;

        //Second approval
        PD_Approval__c smApproval = [SELECT id, Position__c, PD_Request__c FROM PD_Approval__c WHERE PD_Request__c =: appPC.PD_Request__c AND Position__c = 'State Manager'];

        smApproval.Comment__c = 'Testing PC';
        smApproval.Bypass_Validation_Rule__c = TRUE;
        System.debug('Get all the PD Request related IDs: ' + smApproval.PD_Request__c);

        //make it approved
        System.debug('PD1 Position: ' + smApproval.Position__c);
        smApproval.Status__c = 'Approved';
        update smApproval;
        
        Test.stopTest();

        List<PD_Approval__c> allApprovals = [SELECT id, Position__c, PD_Request__c FROM PD_Approval__c WHERE PD_Request__c =: appPC.PD_Request__c]; //2 approvals here
		PD_Request__c req = [SELECT Id, Employee_Name__c, Status__c, Total_Subsidised_Cost__c FROM PD_Request__c WHERE Id =: appPC.PD_Request__c];
        Contact e = [SELECT Id, Annual_PD_Balance__c, Better_Rewards_PD_Balance__c FROM Contact WHERE Id =: req.Employee_Name__c];

        System.assertEquals(2, allApprovals.size());
        System.assertEquals('Approved', req.Status__c);
        System.assertEquals(900, req.Total_Subsidised_Cost__c);
        System.assertEquals(0, e.Annual_PD_Balance__c);
        System.assertEquals(0, e.Better_Rewards_PD_Balance__c);

    }

    @isTest static void testAHAApproval(){
        Test.startTest();
        PD_Approval__c appPC = [SELECT id, Position__c, PD_Request__c FROM PD_Approval__c WHERE PD_Request__r.RecordType.DeveloperName =: 'Allied_Health_Assistant'];

        appPC.Cost_from_Employee_s_Total_PD__c = 0;
        appPC.Additional_BR_Contributions__c = 900;
        appPC.Comment__c = 'Testing PC';
        appPC.Bypass_Validation_Rule__c = TRUE;
        System.debug('Get all the PD Request related IDs: ' + appPC.PD_Request__c);

        //make it approved
        System.debug('PD1 Position: ' + appPC.Position__c);
        appPC.Status__c = 'Approved';
        update appPC;

        //Second approval
        PD_Approval__c smApproval = [SELECT id, Position__c, PD_Request__c FROM PD_Approval__c WHERE PD_Request__c =: appPC.PD_Request__c AND Position__c = 'State Manager'];

        smApproval.Comment__c = 'Testing PC';
        smApproval.Bypass_Validation_Rule__c = TRUE;
        System.debug('Get all the PD Request related IDs: ' + smApproval.PD_Request__c);

        //make it approved
        System.debug('PD1 Position: ' + smApproval.Position__c);
        smApproval.Status__c = 'Approved';
        update smApproval;
        Test.stopTest();

        List<PD_Approval__c> allApprovals = [SELECT id, Position__c, PD_Request__c FROM PD_Approval__c WHERE PD_Request__c =: appPC.PD_Request__c]; //2 approvals here
        PD_Request__c req = [SELECT Id, Employee_Name__c, Status__c, Total_Subsidised_Cost__c FROM PD_Request__c WHERE Id =: appPC.PD_Request__c];
        Contact e = [SELECT Id, Annual_PD_Balance__c, Better_Rewards_PD_Balance__c FROM Contact WHERE Id =: req.Employee_Name__c];

        System.assertEquals(2, allApprovals.size());
        System.assertEquals('Approved', req.Status__c);
        System.assertEquals(900, req.Total_Subsidised_Cost__c);
        System.assertEquals(400, e.Annual_PD_Balance__c);
        System.assertEquals(0, e.Better_Rewards_PD_Balance__c);

    }

    @isTest static void testLeadershipApproval(){
        Test.startTest();
        PD_Approval__c appPC = [SELECT id, Position__c, PD_Request__c FROM PD_Approval__c WHERE PD_Request__r.RecordType.DeveloperName =: 'Leadership'];

        appPC.Cost_from_Employee_s_Total_PD__c = 900;
        appPC.Additional_BR_Contributions__c = 0;
        appPC.Comment__c = 'Testing PC';
        appPC.Bypass_Validation_Rule__c = TRUE;
        System.debug('Get all the PD Request related IDs: ' + appPC.PD_Request__c);

        //make it approved
        System.debug('PD1 Position: ' + appPC.Position__c);
        appPC.Status__c = 'Approved';
        update appPC;
        Test.stopTest();

        List<PD_Approval__c> allApprovals = [SELECT id, Position__c, PD_Request__c FROM PD_Approval__c WHERE PD_Request__c =: appPC.PD_Request__c];
        PD_Request__c req = [SELECT Id, Employee_Name__c, Status__c, Total_Subsidised_Cost__c FROM PD_Request__c WHERE Id =: appPC.PD_Request__c];
        Contact e = [SELECT Id, Annual_PD_Balance__c, Better_Rewards_PD_Balance__c FROM Contact WHERE Id =: req.Employee_Name__c];

        System.assertEquals(1, allApprovals.size());
        System.assertEquals('Approved', req.Status__c);
        System.assertEquals(400, req.Total_Subsidised_Cost__c);
        System.assertEquals(0, e.Annual_PD_Balance__c);
        System.assertEquals(0, e.Better_Rewards_PD_Balance__c);
    }

    @isTest static void testOperationalApproval(){
        Test.startTest();
        PD_Approval__c appPC = [SELECT id, Position__c, PD_Request__c FROM PD_Approval__c WHERE PD_Request__r.RecordType.DeveloperName =: 'Operational'];

        appPC.Cost_from_Employee_s_Total_PD__c = 0;
        appPC.Additional_BR_Contributions__c = 0;
        appPC.Comment__c = 'Testing PC';
        appPC.Bypass_Validation_Rule__c = TRUE;
        System.debug('Get all the PD Request related IDs: ' + appPC.PD_Request__c);

        //make it approved
        System.debug('PD1 Position: ' + appPC.Position__c);
        appPC.Status__c = 'Approved';
        update appPC;

        //Second approval
        PD_Approval__c deptApproval = [SELECT id, Position__c, PD_Request__c FROM PD_Approval__c WHERE PD_Request__c =: appPC.PD_Request__c AND Position__c = 'Department Manager'];

        deptApproval.Comment__c = 'Testing PC';
        deptApproval.Bypass_Validation_Rule__c = TRUE;
        System.debug('Get all the PD Request related IDs: ' + deptApproval.PD_Request__c);

        //make it approved
        System.debug('PD1 Position: ' + deptApproval.Position__c);
        deptApproval.Status__c = 'Approved';
        update deptApproval;
        
        Test.stopTest();

        List<PD_Approval__c> allApprovals = [SELECT id, Position__c, PD_Request__c FROM PD_Approval__c WHERE PD_Request__c =: appPC.PD_Request__c];
        PD_Request__c req = [SELECT Id, Employee_Name__c, Status__c, Total_Subsidised_Cost__c FROM PD_Request__c WHERE Id =: appPC.PD_Request__c];
        Contact e = [SELECT Id, Annual_PD_Balance__c, Better_Rewards_PD_Balance__c FROM Contact WHERE Id =: req.Employee_Name__c];

        System.assertEquals(2, allApprovals.size());
        System.assertEquals('Approved', req.Status__c);
        System.assertEquals(0, req.Total_Subsidised_Cost__c);
        System.assertEquals(400, e.Annual_PD_Balance__c);
        System.assertEquals(0, e.Better_Rewards_PD_Balance__c);
    }

    @isTest static void testLeadershipDenial(){
        Test.startTest();
        PD_Approval__c appPC = [SELECT id, Position__c, PD_Request__c FROM PD_Approval__c WHERE PD_Request__r.RecordType.DeveloperName =: 'Leadership'];

        appPC.Cost_from_Employee_s_Total_PD__c = 0;
        appPC.Additional_BR_Contributions__c = 0;
        appPC.Comment__c = 'Testing PC';
        appPC.Bypass_Validation_Rule__c = TRUE;
        System.debug('Get all the PD Request related IDs: ' + appPC.PD_Request__c);

        //make it approved
        System.debug('PD1 Position: ' + appPC.Position__c);
        appPC.Status__c = 'Denied';
        update appPC;
        Test.stopTest();

        List<PD_Approval__c> allApprovals = [SELECT id, Position__c, PD_Request__c FROM PD_Approval__c WHERE PD_Request__c =: appPC.PD_Request__c];
        PD_Request__c req = [SELECT Id, Employee_Name__c, Status__c, Total_Subsidised_Cost__c FROM PD_Request__c WHERE Id =: appPC.PD_Request__c];
        Contact e = [SELECT Id, Annual_PD_Balance__c, Better_Rewards_PD_Balance__c FROM Contact WHERE Id =: req.Employee_Name__c];

        System.assertEquals(1, allApprovals.size());
        System.assertEquals('Denied', req.Status__c);
        System.assertEquals(0, req.Total_Subsidised_Cost__c);
        System.assertEquals(400, e.Annual_PD_Balance__c);
        System.assertEquals(0, e.Better_Rewards_PD_Balance__c);
    }

}