force-app/main/default/objects/PD_Approval__c/PD_Approval__c.object-meta.xml
<CustomObject>
    <label>PD Approval</label>
    <nameField>
        <displayFormat>PDA-{0000}</displayFormat>
        <label>PD Approval ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PD Approvals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PD_Approval__c/fields/Cost_of_Course__c.field-meta.xml
<CustomField>
    <fullName>Cost_of_Course__c</fullName>
    <formula>PD_Request__r.Cost_of_Course__c</formula>
    <label>Cost of Course</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PD_Approval__c/fields/Course_Date_1__c.field-meta.xml
<CustomField>
    <fullName>Course_Date_1__c</fullName>
    <formula>PD_Request__r.Course_Date_1__c</formula>
    <label>Course Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PD_Approval__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <formula>TEXT(PD_Request__r.Course_Name__c)</formula>
    <label>Course Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PD_Approval__c/fields/PD_Request__c.field-meta.xml
<CustomField>
    <fullName>PD_Request__c</fullName>
    <label>PD Request</label>
    <referenceTo>PD_Request__c</referenceTo>
    <relationshipLabel>PD Approvals</relationshipLabel>
    <relationshipName>PD_Approvals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/PD_Request__c.object-meta.xml
<CustomObject>
    <label>PD Request</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>PD Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PD Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PD_Request__c/fields/Approved_by_Clinical_Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Approved_by_Clinical_Supervisor__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>By ticking this box, you acknowledge that your PD Request has been approved and discussed with your supervisor</inlineHelpText>
    <label>Approved by Supervisor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Approved_by_Direct_Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Approved_by_Direct_Supervisor__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>By ticking this box, you acknowledge that your PD Request has been approved and discussed with your direct supervisor</inlineHelpText>
    <label>Approved by Direct Supervisor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Cost_of_Course__c.field-meta.xml
<CustomField>
    <fullName>Cost_of_Course__c</fullName>
    <label>Cost of Course</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Course_Date_1__c.field-meta.xml
<CustomField>
    <fullName>Course_Date_1__c</fullName>
    <label>Course Date 1</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <inlineHelpText>If your course is not listed, choose &apos;Other&apos; and write your course name in the below box</inlineHelpText>
    <label>Course Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>First Aid / CPR</fullName>
            </value>
            <value>
                <fullName>Mental Health First Aid</fullName>
            </value>
            <value>
                <fullName>Home Modifications</fullName>
            </value>
            <value>
                <fullName>OT Driver Assessor Course</fullName>
            </value>
            <value>
                <fullName>Assistive Technology</fullName>
            </value>
            <value>
                <fullName>Diagnosis specific training</fullName>
            </value>
            <value>
                <fullName>Therapy interventions</fullName>
            </value>
            <value>
                <fullName>Accredited clinical courses</fullName>
            </value>
            <value>
                <fullName>Leadership skills</fullName>
            </value>
            <value>
                <fullName>Professional governing bodies</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <label>Other (Please specify)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Direct_Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Direct_Supervisor__c</fullName>
    <formula>IF(TEXT(Employee_Name__r.Direct_Supervisor__r.Internal_Banding__c) = &apos;Director&apos; &amp;&amp; RecordType.DeveloperName != &apos;Leadership&apos;, &apos;&apos;, Employee_Name__r.Direct_Supervisor__r.enrtcr__Full_Name__c)</formula>
    <label>Direct Supervisor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Employee Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Worker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PD Requests</relationshipLabel>
    <relationshipName>PD_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Internal_Banding__c.field-meta.xml
<CustomField>
    <fullName>Internal_Banding__c</fullName>
    <formula>TEXT(Employee_Name__r.Internal_Banding__c)</formula>
    <label>Internal Banding</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Principal_Clinician__c.field-meta.xml
<CustomField>
    <fullName>Principal_Clinician__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Principal Clinician</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Worker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PD Requests (Principal Clinician)</relationshipLabel>
    <relationshipName>PD_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Regional_Manager__c.field-meta.xml
<CustomField>
    <fullName>Regional_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regional Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Worker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PD Requests (Regional Manager)</relationshipLabel>
    <relationshipName>PD_Requests3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PD_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PD_Request__c/recordTypes/Clinician.recordType-meta.xml
<RecordType>
    <fullName>Clinician</fullName>
    <active>true</active>
    <description>For clinicians and team leaders only</description>
    <label>Clinician</label>
</RecordType>

force-app/main/default/classes/BR_PDApprovalCreationTest.cls
@isTest
public class BR_PDApprovalCreationTest {
    static testMethod void prepareTestData(){
        //Prep the data
        List<RecordType> pdRequestList = new List<RecordType>();
        Map<String,Id> pdRequestType = new Map<String,Id>();

        pdRequestList = [SELECT Id, DeveloperName, SObjectType FROM RecordType WHERE SObjectType = 'PD_Request__c'];
        for(RecordType ids : pdRequestList){
            pdRequestType.put(ids.DeveloperName, ids.Id);
        }

        //Create 6 worker contacts (1 employee, 6 supervisors)
        User x = [SELECT id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1];
        List<Contact> listOfContacts = new List<Contact>();

        for (Integer i = 0 ; i < 8; i++){
            Contact newWorker = TestObjects.createContact(6, 'NDIS');
            newWorker.LastName = 'Worker';
            newWorker.FirstName = 'newW' + String.valueOf(i);
            newWorker.Email = 'newWorker'+ String.valueOf(i) + '@betterrehab.com.au';
            newWorker.enrtcr__User__c = x.Id;

            listOfContacts.add(newWorker);
        }

        insert listOfContacts;

        List<Contact> updatedContacts = new List<Contact>();

        //Set the Ops Mgr to have the internal banding
        Contact om = [SELECT id, Clinical_Supervisor__c, Direct_Supervisor__c FROM Contact WHERE Email = 'newWorker6@betterrehab.com.au'];
        om.Internal_Banding__c = 'Operations Manager';
        updatedContacts.add(om);

        //Set 1 worker to have all 5 supervisors (CS, DS, RM, SM, PC)
        Contact employee = [SELECT id, Clinical_Supervisor__c, Direct_Supervisor__c FROM Contact WHERE Email = 'newWorker0@betterrehab.com.au'];
        Contact cs = [SELECT id, Clinical_Supervisor__c, Direct_Supervisor__c FROM Contact WHERE Email = 'newWorker1@betterrehab.com.au'];
        Contact ds = [SELECT id, Clinical_Supervisor__c, Direct_Supervisor__c FROM Contact WHERE Email = 'newWorker2@betterrehab.com.au'];
        Contact rm = [SELECT id, Clinical_Supervisor__c, Direct_Supervisor__c FROM Contact WHERE Email = 'newWorker3@betterrehab.com.au'];
        Contact sm = [SELECT id, Clinical_Supervisor__c, Direct_Supervisor__c FROM Contact WHERE Email = 'newWorker4@betterrehab.com.au'];
        Contact pc = [SELECT id, Clinical_Supervisor__c, Direct_Supervisor__c FROM Contact WHERE Email = 'newWorker5@betterrehab.com.au'];

        employee.Clinical_Supervisor__c = cs.Id;
        employee.Direct_Supervisor__c = ds.Id;
        updatedContacts.add(employee);
        ds.Direct_Supervisor__c = rm.Id;
        updatedContacts.add(ds);
        rm.Direct_Supervisor__c = sm.Id;
        updatedContacts.add(rm);

        update updatedContacts;

        List<PD_Request__c> PDList = new List<PD_Request__c>();

        Test.startTest();

        //Create PD Request
        PD_Request__c newPD = new PD_Request__c();
        newPD.RecordTypeID = pdRequestType.get('Clinician'); //CLINICIAN
        newPD.Employee_Name__c = employee.Id;
        newPD.Course_Name__c = 'First Aid / CPR';
        newPD.Course_Date_1__c = System.today() + 20;
        newPD.Cost_of_Course__c = 500;
        newPD.Principal_Clinician__c = pc.Id;
        newPD.Regional_Manager__c = rm.Id;
        newPD.Approved_by_Clinical_Supervisor__c = TRUE;
        newPD.Approved_by_Direct_Supervisor__c = TRUE;
        PDList.add(newPD);

        insert PDList;

        Test.stopTest();

        //Get the request based on the known ID
        PD_Request__c request1 = [SELECT id, Status__c FROM PD_Request__c WHERE id =: newPD.Id];

        //Get the list of all approvals with the request ID
        List<PD_Approval__c> allApprovals = [SELECT id FROM PD_Approval__c WHERE PD_Request__c =: request1.Id];

        //There should be 1 PC approval created initially
        System.assertEquals(1, allApprovals.size());
    }
}