force-app/main/default/objects/Session_Communication__c/Session_Communication__c.object-meta.xml
<CustomObject>
    <description>Custom Object used to send Session Communications with Pendula</description>
    <label>Session Communication</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Session Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Communications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Communication__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Session Communications</relationshipLabel>
    <relationshipName>Session_Communications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Communication__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>enrtcr__Session__c</referenceTo>
    <relationshipLabel>Session Communications</relationshipLabel>
    <relationshipName>Session_Communications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Communication__c/fields/Worker_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Worker_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Worker Appointment</label>
    <referenceTo>enrtcr__Worker_Appointment__c</referenceTo>
    <relationshipLabel>Session Communications</relationshipLabel>
    <relationshipName>Session_Communications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SessionUtil.cls
/**
 * Created by ersoz on 2019-06-27.
 */

public class SessionUtil {

    public enum TimeUnit{
        HOURS, MINUTES, SECONDS, DAYS
    }

    public static Long calculateTimeBetween(Datetime startTime, Datetime endTime, TimeUnit unit){

        Long duration = 0;

        if (unit == TimeUnit.DAYS) {
            duration = (endTime.getTime() - startTime.getTime()) / (3600000*24);
        }
        else if (unit == TimeUnit.HOURS){
            duration = (endTime.getTime() - startTime.getTime())/3600000;
        }
        else if (unit == TimeUnit.MINUTES) {
            duration = (endTime.getTime() - startTime.getTime())/60000;
        }
        else if (unit == TimeUnit.SECONDS){
            duration = (endTime.getTime() - startTime.getTime())/1000;
        }
        else{}

        return duration;
    }

    public static Session_Communication__c createSessionCommunicationForWorkerAppointments(
            Id sessionId,
            Id workerAppointmentId,
            Id contactId,
            Id recordTypeId
    ){
        return new Session_Communication__c(
                Session__c = sessionId,
                Worker_Appointment__c = workerAppointmentId,
                Contact__c = contactId,
                RecordTypeId = recordTypeId
        );
    }
}