force-app/main/default/objects/KPI__c/KPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>KPI</label>
</CustomObject>

force-app/main/default/objects/Onboarding__c/Onboarding__c.object-meta.xml
<CustomObject>
    <label>Onboarding</label>
    <nameField>
        <label>Onboarding Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboardings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Onboarding__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Occupational Therapy</fullName>
            </value>
            <value>
                <fullName>Speech Pathology</fullName>
            </value>
            <value>
                <fullName>Physiotherapy</fullName>
            </value>
            <value>
                <fullName>PBS</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Social Work</fullName>
            </value>
            <value>
                <fullName>Allied Health Assistant</fullName>
            </value>
            <value>
                <fullName>Exercise Physiology</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Psychology</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Learning &amp; Development</fullName>
            </value>
            <value>
                <fullName>Talent</fullName>
            </value>
            <value>
                <fullName>Team Leaders</fullName>
                <isActive>false</isActive>
                <label>Team Leaders</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name of the new starter</description>
    <inlineHelpText>Preferred first name</inlineHelpText>
    <label>First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <inlineHelpText>Preferred last name</inlineHelpText>
    <label>Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <formula>Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/Role_Title__c.field-meta.xml
<CustomField>
    <fullName>Role_Title__c</fullName>
    <description>Employee role title</description>
    <label>Role Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>enrtcr__Site__c</referenceTo>
    <relationshipLabel>Onboardings</relationshipLabel>
    <relationshipName>Onboardings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/User_Apex_Run__c.field-meta.xml
<CustomField>
    <fullName>User_Apex_Run__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Apex Run</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Phone_Number__c/Phone_Number__c.object-meta.xml
<CustomObject>
    <label>Phone Number</label>
    <nameField>
        <label>Phone Number Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phone Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FutureListUser.cls
public class FutureListUser {
	@future
    public static void insertUsers(List<Id> OnboarderIDs) {
        //Get the profile ID for system Admin
        Profile Basic = [SELECT Id FROM Profile WHERE Name='Enrite Care - Basic' limit 1];
        Profile Standard = [SELECT Id FROM Profile WHERE Name='Enrite Care - Standard' limit 1];
        Profile SysAdmin = [SELECT Id FROM Profile WHERE Name='System Administrator' limit 1];
        
        UserRole ClinBasic = [SELECT Id FROM UserRole WHERE Name='Clinicians (Basic)' limit 1];
        UserRole TLStandard = [SELECT Id FROM UserRole WHERE Name='Team Lead (Standard)' limit 1];
        UserRole MgmtAdvanced = [SELECT Id FROM UserRole WHERE Name='Management/Finance (Advanced)' limit 1];
        
        List<User> usersToCreate = new List<User>();
        for (Id OnboarderID : OnboarderIDs) {
            //initialise a new user using User object
            User newUser = new User();
            
            //grab the onboarder from the list view, should be only one incoming onboarder for every trigger
            Onboarding__c OnboarderDetails = [SELECT User_Apex_Run__c, Last_Name__c, First_Name__c,Email__c , Phone_Number__c, State__c, Department__c, Site__c, Office__c, Role_Title__c FROM Onboarding__c WHERE Id =: OnboarderID];
            
            Id UserRoleId = null;
            Id ProfileId = null;
            Integer KPI = 0;
            String Site = OnboarderDetails.Office__c;
            String TimeZone = '';
            String UserAlias = getAlias(OnboarderDetails.First_Name__c, OnboarderDetails.Last_Name__c);
            
            //Set the userRoleId based on their department
            if (OnboarderDetails.Department__c == 'Team Leaders' || OnboarderDetails.Department__c == 'Marketing' || OnboarderDetails.Department__c == 'Human Resources') {
                UserRoleId = TLStandard.Id;
            } else if (OnboarderDetails.Department__c == 'Management' || OnboarderDetails.Department__c == 'Information Technology' || OnboarderDetails.Department__c == 'Administration') {
                UserRoleId = MgmtAdvanced.Id;
            } else {
                UserRoleId = ClinBasic.Id;
            }
            
            //set the Profile based on their department
            if (OnboarderDetails.Department__c == 'Team Leaders' || OnboarderDetails.Department__c == 'Management') {
                ProfileId = Standard.Id;
            } else if (OnboarderDetails.Department__c == 'Information Technology' || OnboarderDetails.Department__c == 'Administration') {
                ProfileId = SysAdmin.Id;
            } else {
                ProfileId = Basic.Id;
            }
            
            //Get the correct KPI
            if (OnboarderDetails.Department__c == 'Occupational Therapy') {
                KPI = 30;
            } else if (OnboarderDetails.Department__c == 'Physiotherapy' || OnboarderDetails.Department__c == 'Speech Pathology' || OnboarderDetails.Department__c == 'PBS' || OnboarderDetails.Department__c == 'Exercise Physiology' || OnboarderDetails.Department__c == 'Social Work' || OnboarderDetails.Department__c == 'Allied Health Assistant') {
                KPI = 28;
            }
            
            //Get the correct TimeZone
            if (OnboarderDetails.State__c == 'NSW' || OnboarderDetails.State__c == 'VIC' || OnboarderDetails.State__c == 'ACT') {
                TimeZone = 'Australia/Sydney';
            } else if (OnboarderDetails.State__c == 'QLD') {
                TimeZone = 'Australia/Brisbane';
            } else if (OnboarderDetails.State__c == 'WA') {
                TimeZone = 'Australia/Perth';
            }
            
            
            //initialise the new user with the details of the onboarder
            newUser.LastName = OnboarderDetails.Last_Name__c;
            newUser.FirstName = OnboarderDetails.First_Name__c;
            newUser.Country = 'Australia';
            newUser.CompanyName = 'Better Rehab';
            newUser.Email = OnboarderDetails.Email__c;
            newUser.MobilePhone = OnboarderDetails.Phone_Number__c;
            newUser.Title = OnboarderDetails.Role_Title__c;
            newUser.KPI__c = KPI;
            newUser.State = OnboarderDetails.State__c;
            newUser.Site__c = Site;
            newUser.Username = OnboarderDetails.Email__c;
            if (OnboarderDetails.Department__c != 'Management' && OnboarderDetails.Department__c != 'Team Leaders') {
                    newUser.Department = OnboarderDetails.Department__c;
                }
            newUser.CommunityNickName = OnboarderDetails.First_Name__c + OnboarderDetails.Last_Name__c;
            newUser.EmailEncodingKey = 'ISO-8859-1';
            newUser.ProfileId = ProfileId;
            newUser.UserRoleId = UserRoleId;
            newUser.TimeZoneSidKey = TimeZone;
            newUser.LocaleSidKey = 'en_AU';
            newUser.LanguageLocaleKey = 'en_US';
            newUser.UserPreferencesReceiveNoNotificationsAsApprover = false;
            newUser.Alias = UserAlias;
            
            usersToCreate.add(newUser);
        }
        //insert the newUser
       	insert usersToCreate;
    }
    
    private static String getAlias(String First, String Last) {
        String initalFirst = First.substring(0, 1);
        String LastBit = 'Failed';
        if (Last.length() < 7) {
            LastBit = Last;
        } else {
            LastBit = Last.substring(0, 7);
        }
        
        String alias = initalFirst + LastBit;
        
        return alias;
    }
}