force-app/main/default/objects/Xero_Private_Settngs__c/Xero_Private_Settngs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Xero Private Settngs</label>
</CustomObject>

force-app/main/default/objects/Xero_Private_Settngs__c/fields/Access_Token_URL__c.field-meta.xml
<CustomField>
    <fullName>Access_Token_URL__c</fullName>
    <defaultValue>&quot;https://tutorssa--enritedev1.my.salesforce.com/servlet/servlet.ExternalRedirect?url=https%3A%2F%2Fidentity.xero.com%2Fconnect%2Ftoken&amp;&quot;</defaultValue>
    <label>Access Token URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Xero_Private_Settngs__c/fields/Private_Key_2_0__c.field-meta.xml
<CustomField>
    <fullName>Private_Key_2_0__c</fullName>
    <label>Private Key 2.0</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Xero_Private_Settngs__c/fields/Private_Key__c.field-meta.xml
<CustomField>
    <fullName>Private_Key__c</fullName>
    <label>Consumer Secret</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Xero_Private_Settngs__c/fields/Public_Key_2_0__c.field-meta.xml
<CustomField>
    <fullName>Public_Key_2_0__c</fullName>
    <label>Public Key 2.0</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Xero_Private_Settngs__c/fields/Public_Key__c.field-meta.xml
<CustomField>
    <fullName>Public_Key__c</fullName>
    <label>Consumer Key</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/XeroCallBackExtensionTest.cls
/**
 * Created by Enrite Solutions on 9/02/2021.
 */

@IsTest
private class XeroCallBackExtensionTest {
    @IsTest
    static void testFailCallback1() {
        insert new Xero_Private_Settngs__c(
                Private_Key_2_0__c = '11',
                Public_Key__c = '11',
                Public_Key_2_0__c = '11',
                Private_Key__c = '11',
                Endpoint__c = 'https://api.xero.com/api.xro/2.0/',
                Access_Token_URL__c = 'https://identity.xero.com/connect/token'
        );
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Account acc = XeroCallBackExtension.getDefaultXeroAccount();
        acc.Xero_Access_Token__c = '111';
        acc.Xero_Tenant_ID__c = '111';
        acc.Xero_Refresh_ID__c = '111';
        acc.Xero_Authorisation_Code__c = '111';

        upsert acc;


        Test.startTest();

        XeroCallBackExtension b = new XeroCallBackExtension();
        b.callback();

        Test.stopTest();
    }

    @IsTest
    static void testCallBack() {
        insert new Xero_Private_Settngs__c(
                Private_Key_2_0__c = '11',
                Public_Key__c = '11',
                Public_Key_2_0__c = '11',
                Private_Key__c = '11',
                Endpoint__c = 'https://api.xero.com/api.xro/2.0/',
                Access_Token_URL__c = 'https://identity.xero.com/connect/token'
        );
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Account acc = XeroCallBackExtension.getDefaultXeroAccount();
        acc.Xero_Access_Token__c = '111';
        acc.Xero_Tenant_ID__c = '111';
        acc.Xero_Refresh_ID__c = '111';
        acc.Xero_Authorisation_Code__c = '111';

        upsert acc;


        Test.startTest();
        PageReference pg = new PageReference('/apex/callback');
        pg.getParameters().put(XeroCallBackExtension.PARAM_CODE, '1122Code');

        Test.setCurrentPage(pg);
        XeroCallBackExtension b = new XeroCallBackExtension();
        b.callback();

        Test.stopTest();
    }
}