force-app/main/default/objects/Setting__c/Setting__c.object-meta.xml
<CustomObject>
    <label>Setting</label>
    <nameField>
        <label>Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Setting__c/fields/Settings__c.field-meta.xml
<CustomField>
    <fullName>Settings__c</fullName>
    <label>Settings</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/br_settingsTest.cls
@isTest
private class br_settingsTest {
    static testMethod void validateAddKeyToMap() {
      	Setting__c kpiflow = new Setting__c();
        kpiFlow.Name = 'kpiFlow';
        kpiFlow.Settings__c = '{"baseKPI":"25","testKey2":"test value 2","testKey1":"test value 1","prevStartPeriod":"12/12/2020","repetition":"20","startDate":"12/12/2020","project":"kpiFlow","endDate":"12/13/2022"}';
        
        insert kpiFlow;
        
        Test.startTest();
        PageReference userPage = Page.BR_Settings;
        Test.setCurrentPage(userPage);
        userPage.getParameters().put('Id', String.valueOf(kpiFlow.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(kpiFlow);
        br_settings page = new br_settings(sc);
        
        page.newKeyName = 'thisNewKey';
        page.addKeyToMap();
        page.submit();
        
        Test.stopTest();
        
        System.assertEquals(true, Utility.JSONtoMap(kpiFlow.Settings__c).keyset().contains('thisNewKey')); 
    }
}