force-app/main/default/objects/Onboarding__c/Onboarding__c.object-meta.xml
<CustomObject>
    <label>Onboarding</label>
    <nameField>
        <label>Onboarding Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboardings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Onboarding__c/fields/Clinical_Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Supervisor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Worker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Onboardings (Clinical Supervisor)</relationshipLabel>
    <relationshipName>Onboardings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Occupational Therapy</fullName>
            </value>
            <value>
                <fullName>Speech Pathology</fullName>
            </value>
            <value>
                <fullName>Physiotherapy</fullName>
            </value>
            <value>
                <fullName>PBS</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Social Work</fullName>
            </value>
            <value>
                <fullName>Allied Health Assistant</fullName>
            </value>
            <value>
                <fullName>Exercise Physiology</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Psychology</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Learning &amp; Development</fullName>
            </value>
            <value>
                <fullName>Talent</fullName>
            </value>
            <value>
                <fullName>Team Leaders</fullName>
                <isActive>false</isActive>
                <label>Team Leaders</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name of the new starter</description>
    <inlineHelpText>Preferred first name</inlineHelpText>
    <label>First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Intersex</fullName>
            </value>
            <value>
                <fullName>Declined to Answer</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
            <value>
                <fullName>Non-Binary</fullName>
            </value>
            <value>
                <fullName>Unknown/Did Not Share</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <inlineHelpText>Preferred last name</inlineHelpText>
    <label>Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <formula>Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Office</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/User_Apex_Run__c.field-meta.xml
<CustomField>
    <fullName>User_Apex_Run__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Apex Run</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Phone_Number__c/Phone_Number__c.object-meta.xml
<CustomObject>
    <label>Phone Number</label>
    <nameField>
        <label>Phone Number Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phone Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OnboardingUserController.cls
public with sharing class OnboardingUserController {
	// Constructor - this is only required/used if the autoRun function does not work
	private onboarding__c onboarder;
    public String message {get; set;}    
    
    public OnboardingUserController(ApexPages.StandardController stdController) {
        this.onboarder = (onboarding__c)stdController.getRecord();
    }
    
    //VF Page will invoke this method
    public PageReference autoRun() {
        String theId = ApexPages.currentPage().getParameters().get('id');
        
        if (theId == null) {
            //no id was given from button to VF page to this controller - display VF page content
            message = 'No onboarding record is detected. Please open an onboarding record and try again.';
            return null;
        }
        
        this.onboarder = [SELECT id, User_Apex_Run__c, Email__c, First_Name__c, Last_Name__c, Phone_Number__c, State__c, Department__c, Office__c, Clinical_Supervisor__c, Gender__c FROM onboarding__c WHERE id =: theId LIMIT 1];
        if (this.onboarder.User_Apex_Run__c == true) {
            System.debug('The user Apex Run checkbox is marked as true. It looks like Apex user creation code has been run on this new starter already');
            message = 'It looks like this action has been run on this new starter. If you believe this is wrong, please double check that their User profile has not been created. After that, untick the User Apex Run tickbox and try again.';
        	return null;
        }
        
        String onboarderEmail = this.onboarder.Email__c;
        User[] users = [SELECT Id FROM User WHERE Email =: onboarderEmail];
        
        if ( users.size() > 0 ) {
            System.debug('We found a user with the same email address as this onboarder');
            message = 'We found a user with the same email address as this onboarder. Please double check the email address and try again.';
            return null;
        }
        
        if(checkRemainingLicenses() == FALSE){
            System.debug('checkRemainingLicense Result: ' + checkRemainingLicenses());
            message = 'There is no remaining Lumary license. Please order new Lumary basic licenses and try again.';
            return null;
        }
        
        createUser(theId);
        onboarder.User_Apex_Run__c = true;
        update onboarder;
        PageReference pageRef = new PageReference('/' + theId);
        pageRef.setRedirect(true);
        return pageRef;
    }
    
    public String getNoIssue(){
        return 'Issue cannot be detected. Please contact your Salesforce Developer.';
    }
    
    private void createUser(Id onboarderID) {
        FutureUser.insertUser(onboarderID);
    }
    
    public boolean checkRemainingLicenses(){
        //Get the package license
        Organization sandbox = [SELECT IsSandbox FROM Organization LIMIT 1];
        PackageLicense pckgLicense = [SELECT Id, AllowedLicenses, UsedLicenses FROM PackageLicense WHERE NamespacePrefix = 'enrtcr'];
        if(sandbox.IsSandbox == FALSE){            
            if(pckgLicense.AllowedLicenses - pckgLicense.UsedLicenses <= 0){
                return FALSE;
            } else {
                return TRUE;
            } 
        } else {
            return TRUE;
        }
    }
}