force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>enrtcr__Site__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upcoming</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Stolen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Slot__c/Slot__c.object-meta.xml
<CustomObject>
    <label>Slot</label>
    <nameField>
        <label>Slot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Slot__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Slots (Client)</relationshipLabel>
    <relationshipName>Slots1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/Destination_Site__c.field-meta.xml
<CustomField>
    <fullName>Destination_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Site</label>
    <referenceTo>enrtcr__Site__c</referenceTo>
    <relationshipLabel>Slots</relationshipLabel>
    <relationshipName>Slots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Slots</relationshipLabel>
    <relationshipName>Slots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BR_ResourceSlotController.cls
public class BR_ResourceSlotController {
    @AuraEnabled
    public static Map<String, String> a_init(){
        Map<String, String> queries = new Map<String, String>();
        User u = [SELECT id, State FROM User WHERE id =: UserInfo.getUserId()];
        System.debug('----------' + u.State);
        //
        try {
            String now = DateTime.now().format('yyyy-MM-dd');
            String userState = u.State;
            System.debug(userState);
            String resourceQuery = 'AND Status__c = \'Active\' AND Tier__c = \'1\' AND (Site__c = NULL OR Site__r.enrtcr__Business_State__c = \''+userState+'\') AND (Expiry_Date__c = NULL OR Expiry_Date__c >= '+now+')';

            queries.put('resource', resourceQuery);

            return queries;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

	@AuraEnabled
    public static Slot__c a_createSlot(String requestObject) {
        SlotCreate req = (SlotCreate)JSON.deserialize(requestObject, SlotCreate.Class);

        Slot__c s = new Slot__c();
        s.OwnerId = req.userId;
        s.Resource__c = req.resourceId;
        s.Client__c = req.clientId;
        s.Destination_Site__c = req.destinationSiteId;
        s.Start_Time__c = Utility.GMTStringToGMTdt(req.startDt);
        s.End_Time__c = Utility.GMTStringToGMTdt(req.endDt);

        try {
        	insert s;
        } catch (DMLException err) {
            System.debug(err.getMessage());
            throw new AuraHandledException(err.getMessage());
        }


        return getSlot(s.Id);
    }

    @AuraEnabled
    public static Slot__c a_updateSlot(String updateJSON) {
        SlotUpdate req = (SlotUpdate)JSON.deserialize(updateJSON, SlotUpdate.Class);

        Slot__c s = getSlot(req.slotId);
        if (req.destinationSite != 'NULL') {
        	s.Destination_Site__c = req.destinationSite;
        }
        s.Start_Time__c = Utility.GMTStringToGMTdt(req.startTime);
        s.End_Time__c = Utility.GMTStringToGMTdt(req.endTime);

        try {
        	update s;
        } catch (DMLException err) {
            System.debug(err.getMessage());
            throw new AuraHandledException(err.getMessage());
        }


        return getSlot(s.Id);
    }

    @AuraEnabled
    public static void a_deleteSlot(Id slotId) {
    	Slot__c slot = [SELECT id FROM Slot__c WHERE id =: slotId];

        try {
            delete slot;
        } catch (DMLException err) {
            throw new AuraHandledException(err.getMessage());
        }
    }

    @AuraEnabled
    public static Slot__c a_getSlot(Id slotId) {
        return getSlot(slotId);
    }

    private static Slot__c getSlot(Id slotId) {
        return [SELECT id, OwnerId, Owner.Name, Destination_Site__c, Destination_Site__r.Name, Resource__c,Resource__r.Name, Start_Time__c, End_Time__c, Client__c, Client__r.Name FROM Slot__c WHERE id =: slotId];
    }
    class SlotCreate {
        String resourceId;
        String userId;
        String clientId;
        String destinationSiteId;
        String startDt;
        String endDt;
    }

    class SlotUpdate {
        String slotId;
        String startTime;
        String endTime;
        String destinationSite;
    }
}