force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <label>Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>enrtcr__Site__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Upcoming</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Stolen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BR_ResourceDAO.cls
public with sharing class BR_ResourceDAO {
    public static List<Resource__c> getActiveAndTierOneResourcesByState(String state) {
        return [
            SELECT id, Name, Site__c, Site__r.enrtcr__Business_State__c, Status__c, Tier__c, Type__c FROM Resource__c
            WHERE Status__c = 'Active'
            AND Tier__c = '1'
            AND (Expiry_Date__c = NULL OR Expiry_Date__c >= : System.today())
            AND Site__r.enrtcr__Business_State__c =: state
        ];
    }

    public static List<Resource__c> getActiveAndTierOneResources() {
        return [
            SELECT id, Name, Site__c, Site__r.enrtcr__Business_State__c, Status__c, Tier__c, Type__c FROM Resource__c
            WHERE Status__c = 'Active'
            AND Tier__c = '1'
            AND (Expiry_Date__c = NULL OR Expiry_Date__c >= : System.today())
        ];
    }

    public static List<Resource__c> getActiveAndTierOneResourcesWithNullSite() {
        return [
            SELECT id, Name, Site__c, Status__c, Tier__c, Type__c FROM Resource__c
            WHERE Status__c = 'Active'
            AND Tier__c = '1'
            AND (Expiry_Date__c = NULL OR Expiry_Date__c >= : System.today())
            AND Site__c = NULL
        ];
    }
}