force-app/main/default/objects/Offboarding__c/Offboarding__c.object-meta.xml
<CustomObject>
    <label>Offboarding</label>
    <nameField>
        <label>Offboarding ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offboardings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offboarding__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>2700</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Offboarding__c/fields/Direct_Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Direct_Supervisor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Direct Supervisor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Worker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Offboardings</relationshipLabel>
    <relationshipName>Offboardings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offboarding__c/fields/Exit_Date__c.field-meta.xml
<CustomField>
    <fullName>Exit_Date__c</fullName>
    <label>Exit Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Offboarding__c/fields/Internal_Banding__c.field-meta.xml
<CustomField>
    <fullName>Internal_Banding__c</fullName>
    <formula>TEXT(Offboarding_Name__r.Internal_Banding__c)</formula>
    <label>Internal Banding</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Offboarding__c/fields/Offboarding_Name__c.field-meta.xml
<CustomField>
    <fullName>Offboarding_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Offboarding Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Worker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Offboardings (Offboarding Name)</relationshipLabel>
    <relationshipName>Offboardings2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offboarding__c/fields/Offboarding_Type__c.field-meta.xml
<CustomField>
    <fullName>Offboarding_Type__c</fullName>
    <label>Offboarding Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Involuntary</fullName>
            </value>
            <value>
                <fullName>Voluntary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Offboarding__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Site</label>
    <referenceTo>enrtcr__Site__c</referenceTo>
    <relationshipLabel>Offboardings</relationshipLabel>
    <relationshipName>Offboardings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/offboardingTriggerHandlerTest.cls
@isTest
private class offboardingTriggerHandlerTest {
    static testMethod void validateTaskCreation() {

        User u = [SELECT id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1];

        Contact newWorker = TestObjects.createContact(6, 'NDIS');
        newWorker.LastName = 'super';
        newWorker.FirstName = 'clin';
        newWorker.Email = 'clinsup@betterrehab.com.au';
        newWorker.enrtcr__User__c = u.Id;
        newWorker.Internal_Banding__c = 'Regional Manager';
        insert newWorker;

        Contact ds = TestObjects.createContact(6, 'NDIS');
        ds.LastName = 'ds';
        ds.FirstName = 'worer';
        ds.Email = 'dsUP@betterrehab.com.au';
        insert ds;

        enrtcr__Site__c site = TestObjects.createSite(2);
        site.Office_Admin__c = u.Id;
        insert site;

        Offboarding__c newOffboarder = new Offboarding__c();
        newOffboarder.Name = 'newP person';
        newOffboarder.Offboarding_Name__c = newWorker.Id;
        newOffboarder.Offboarding_Type__c = 'Voluntary';
        newOffboarder.Exit_Date__c = System.today();
        newOffboarder.Comments__c = 'comments';
        newOffboarder.Site__c = site.Id;
        newOffboarder.Direct_Supervisor__c = ds.Id;

        Test.startTest();
        insert newOffboarder;
        Test.stopTest();

        Task[] tasks = [SELECT id FROM Task WHERE WhatId =: newOffboarder.Id];
        System.assertEquals(20, tasks.size());
    }
}